name: Book Marker Preview Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  BASE_API_URL: ${{ secrets.BASE_API_URL }}
  IMG_UPLOAD_URL: ${{ secrets.IMG_UPLOAD_URL }}
  IMG_UPLOAD_KEY: ${{ secrets.IMG_UPLOAD_KEY }}
  RECOMMEND_BOOK_API_URL: ${{ secrets.RECOMMEND_BOOK_API_URL }}
on:
  pull_request:
    branches:
      - develop
jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Set up environment variables
        run: |
          echo "BASE_API_URL=${{ secrets.BASE_API_URL }}" >> $GITHUB_ENV
          echo "IMG_UPLOAD_URL=${{ secrets.IMG_UPLOAD_URL }}" >> $GITHUB_ENV
          echo "IMG_UPLOAD_KEY=${{ secrets.IMG_UPLOAD_KEY }}" >> $GITHUB_ENV

      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
