name: Vercel Production Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  pull_request:
    branches:
      - main
jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Set up environment variables
        run: |
          echo "BASE_API_URL=${{ secrets.BASE_API_URL }}" >> $GITHUB_ENV
          echo "IMG_UPLOAD_URL=${{ secrets.IMG_UPLOAD_URL }}" >> $GITHUB_ENV
          echo "IMG_UPLOAD_KEY=${{ secrets.IMG_UPLOAD_KEY }}" >> $GITHUB_ENV
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
